### ISSUE TITLE
How to Batch Training？

### ISSUE THREAD

**Issue by GuoxingYan** [TonyXuQAQ/RNGDetPlusPlus#11]
I have reproduced the training code, but only one 128 x 128 input is supported, and the batchsize is 1. I do not know how to perform the batch operation. After all, the quantity of matching is inconsistent.

**Comment by TonyXuQAQ** [comment]
Please wait for the training code of this work.

**Comment by TonyXuQAQ** [comment]
The sampling and training codes are released. This issue is closed.
