### ISSUE TITLE
CNN backones

### ISSUE THREAD

**Issue by GuoxingYan** [TonyXuQAQ/RNGDetPlusPlus#15]
in backbone.py
`    def __init__(self, backbone: nn.Module, train_backbone: bool, num_channels: int, return_interm_layers: bool, history: bool):`

1. I found that the history parameter was not actually used.
2. Focal Los is not used in the actual training code.

**Comment by TonyXuQAQ** [comment]
The code still has redundancy, please ignore those duplicated codes. We will try to refine the code in the future.
