### ISSUE TITLE
 This is a problem about rtree.go

### ISSUE THREAD

**Issue by wwcc1107** [TonyXuQAQ/RNGDetPlusPlus#19]
when i run ./apls.bash .i meet this problem:
metrics/apls/main.go:106:50: cannot use rtreego.Point{...}.ToRect(tol) (type rtreego.Rect) as type *rtreego.Rect in return argument
metrics/apls/main.go:360:13: cannot use &gNode (type *gpsnode) as type rtreego.Spatial in argument to rt.Insert:

**Comment by TonyXuQAQ** [comment]
Make sure you do the evaluation outside docker. I cannot make it work in docker.

**Comment by wwcc1107** [comment]
> Make sure you do the evaluation outside docker. I cannot make it work in docker.
thank you,but i run ./apls.bash outside docker,meets the same questions:
========================159======================
convert success
convert success
# command-line-arguments
apls/main.go:107:49: cannot use rtreego.Point literal.ToRect(tol) (type rtreego.Rect) as type *rtreego.Rect in return argument
apls/main.go:356:13: cannot use &gNode (type *gpsnode) as type rtreego.Spatial in argument to rt.Insert:
	*gpsnode does not implement rtreego.Spatial (wrong type for Bounds method)
		have Bounds() *rtreego.Rect
		want Bounds() rtreego.Rect
apls/main.go:373:28: impossible type assertion:
	*gpsnode does not implement rtreego.Spatial (wrong type for Bounds method)
		have Bounds() *rtreego.Rect
		want Bounds() rtreego.Rect
apls/main.go:377:25: impossible type assertion:
	*gpsnode does not implement rtreego.Spatial (wrong type for Bounds method)
		have Bounds() *rtreego.Rect
		want Bounds() rtreego.Rect
apls/main.go:378:36: impossible type assertion:
	*gpsnode does not implement rtreego.Spatial (wrong type for Bounds method)
		have Bounds() *rtreego.Rect
		want Bounds() rtreego.Rect
apls/main.go:381:32: impossible type assertion:
	*gpsnode does not implement rtreego.Spatial (wrong type for Bounds method)
		have Bounds() *rtreego.Rect
		want Bounds() rtreego.Rect
have you meet the same question?thank you

**Comment by TonyXuQAQ** [comment]
I have not met the above problem. The evaluation code is provided by [sat2graph](https://github.com/songtaohe/Sat2Graph), and I directly used their codes for evaluation. 

Have you correctly installed the dependency github.com/dhconnelly/rtreego?

**Comment by wwcc1107** [comment]
> 

ok. Thank you . I  have solved this problem,it is a problem about rtreego package. I have correctly installed it.
