### ISSUE TITLE
the dataset link can't open

### ISSUE THREAD

**Issue by Dawn-bin** [TonyXuQAQ/RNGDetPlusPlus#2]
hi, the dataset link can't open. Would you share with other link(like Google Drive)?

**Comment by TonyXuQAQ** [comment]
It seems that the raw link provided by Sat2Graph is not valid anymore. It worked when the code was first released. We have uploaded the data to Google Drive and the data could be downloaded now.

**Comment by Dawn-bin** [comment]
thank U for reply.
