### ISSUE TITLE
If there are some turning points ahead, How do you find the turning point?

### ISSUE THREAD

**Issue by GuoxingYan** [TonyXuQAQ/RNGDetPlusPlus#6]
If there are some turning points ahead, we find the turning point that is closest to vt as (vt1+1)∗ (subfigure (b) of Fig. 7).

How did you achieve this? Is the implementation of this step in the published code?

I understand that the path has been simplified in the process of creating the graph.

We look forward to your reply.

**Comment by TonyXuQAQ** [comment]
Hi Yan,

We calculate the orientation value of each pixel (i.e., a unit vector). If the turning angle between a pixel $u$ and $v_t$ larger than a threshold, we can know that a curve road is met.

This is implemented in our code. Each edge object has an attribute ```orientation``` to record corresponding information.
