### ISSUE TITLE
How's the effect at the regular tic junction?

### ISSUE THREAD

**Issue by GuoxingYan** [TonyXuQAQ/RNGDetPlusPlus#7]
在常规井字路口的效果怎么样？

**Comment by TonyXuQAQ** [comment]
Do you mean T junctions? Here are some testing results of RNGDet++. You can also try our inference code by yourself. Hope these visualizations help.

GT of example one             |  RNGDet++ prediction of example one
:-------------------------:|:-------------------------:
![49_gt](https://user-images.githubusercontent.com/33851435/198289033-9f40b26f-c633-4184-9de1-80ee09041753.png)  | ![49_RNGDet++](https://user-images.githubusercontent.com/33851435/198289079-25b6d896-3786-46cd-b48e-2c9a90f80c81.png)

GT of example two             |  RNGDet++ prediction of example two
:-------------------------:|:-------------------------:
![88_gt](https://user-images.githubusercontent.com/33851435/198290836-dde6ebac-fabf-4d16-9d4f-83b1bf4c25d9.png) | ![88_RNGDet++](https://user-images.githubusercontent.com/33851435/198290913-2f12dc82-f0b7-49d4-8d32-d90ebac1d8ee.png)

**Comment by GuoxingYan** [comment]
Thank you very much for your reply.
